import streamlit as st
from streamlit.components import v1 as st_comp

st.set_page_config(layout="wide", page_title="A quick physics 101")

st.title("A quick physics primer")

st_comp.iframe(
   src= "https://opendata.atlas.cern/docs/documentation/introduction/SM_and_beyond",
   height= 5000,
   scrolling=True
)

st.markdown(
"""
# Feeling confused?
Don't worry!! Even qualified particle physicists can find it a bit much. 
For us, this makes it all the more intriguing, and motivates us to keep 
studying why our intuition isn't always the straightforward answer...
"""
)

st.image("images/fundamental_forces_2x.png")

st.markdown(
"""
# What is dark matter?
## We don't know!
### But we know how it interects
This is because astronomers have observed its effects on the rotations of 
galaxies since the 1970s. 
"""
)

st.image("images/galaxycurve.jpg")

#st_comp.iframe(
#   src="https://home.cern/science/physics/dark-matter",
#   height=1500,
#   scrolling=True
#)

st.markdown(
"""
**The following information is taken from [CERN's page on the topic](https://home.cern/science/physics/dark-matter)***

Galaxies in our universe seem to be achieving an impossible feat. They are rotating with such speed that the gravity generated by their observable matter could not possibly hold them together; they should have torn themselves apart long ago. The same is true of galaxies in clusters, which leads scientists to believe that something we cannot see is at work. They think something we have yet to detect directly is giving these galaxies extra mass, generating the extra gravity they need to stay intact. This strange and unknown matter was called “dark matter” since it is not visible.

## Dark matter
Unlike normal matter, dark matter does not interact with the electromagnetic force. This means it does not absorb, reflect or emit light, making it extremely hard to spot. In fact, researchers have been able to infer the existence of dark matter only from the gravitational effect it seems to have on visible matter. Dark matter seems to outweigh visible matter roughly six to one, making up about 27% of the universe. Here's a sobering fact: The matter we know and that makes up all stars and galaxies only accounts for 5% of the content of the universe! But what is dark matter? One idea is that it could contain "supersymmetric particles" – hypothesized particles that are partners to those already known in the Standard Model. Experiments at the Large Hadron Collider (LHC) may provide more direct clues about dark matter.

Many theories say the dark matter particles would be light enough to be produced at the LHC. If they were created at the LHC, they would escape through the detectors unnoticed. However, they would carry away energy and momentum, so physicists could infer their existence from the amount of energy and momentum “missing” after a collision. Dark matter candidates arise frequently in theories that suggest physics beyond the Standard Model, such as supersymmetry and extra dimensions. One theory suggests the existence of a “Hidden Valley”, a parallel world made of dark matter having very little in common with matter we know. If one of these theories proved to be true, it could help scientists gain a better understanding of the composition of our universe and, in particular, how galaxies hold together.

## Dark energy
Dark energy makes up approximately 68% of the universe and appears to be associated with the vacuum in space. It is distributed evenly throughout the universe, not only in space but also in time – in other words, its effect is not diluted as the universe expands. The even distribution means that dark energy does not have any local gravitational effects, but rather a global effect on the universe as a whole. This leads to a repulsive force, which tends to accelerate the expansion of the universe. The rate of expansion and its acceleration can be measured by observations based on the Hubble law. These measurements, together with other scientific data, have confirmed the existence of dark energy and provide an estimate of just how much of this mysterious substance exists.
"""
)

if st.button("Next page"):
  st.switch_page("pages/3_Analysis_example.py")
if st.button("Previous page"):
  st.switch_page("pages/1_Intro.py")
